[package]
name = "lambda-flow-simple"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
airtable-flows = "0.1"
http_req_wasi = "0.10"
lambda-flows = "0.1"
serde_json = "1.0"
slack-flows = "0.1"
